### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ElisaGDR** [4GeeksAcademy/iirenevs-modelo-datos-instagram#1]
Bien hecho @iireneVS . Te sugiero algunos cambios para que funcione correctamente:

- En la class `Followers` : sobraría la línea 43 y faltarían estas dos: 
`user_follower =  relationship("Users", foreign_keys=["user_follower_id"])`
`user_following = relationship("Users", foreign_keys=["user_following_id "])`
- En la class `Like` debes cambiar `Post.id` por `post.id`

;)

**Comment by iireneVS** [comment]
Voy a ello!!!!
